### PR TITLE
Remove the packages instances list 

### PR DESCRIPTION
**Pull request by tfoote**
that's not necessary with cross references available from all instance pages

This saves reduced approximately 30% of the pages on the site which makes it smaller and jekyll will use many less resources.

Current:
Screenshot from 2022-04-11 16-16-27

After:
Screenshot from 2022-04-11 16-16-35

Dropdown still active and all instances still cross referenced and accessible: 
Screenshot from 2022-04-11 16-17-59

The packages list page is gone, but it's only referenced from the removed link and is also redundant with the drop down content.
Screenshot from 2022-04-11 16-21-08

For most packages this is a list of one: 

Screenshot from 2022-04-11 17-47-58

### CODE REVIEW

**Comment by tfoote** [comment]
@clalancette This has the potential to remove ~30% of our memory usage and generation time. There's more to go but it's a useful step forward.

**Comment by clalancette** [comment]
Sorry, this one fell off my radar.

What do the instances represent, anyway?  Looking at the `conman_msgs` one, there are two different "instances", which seem to correspond to two different source repositories.  Is that meant to show all of the source repositories that contain a package of this name?

**Comment by tfoote** [comment]
Yeah, the vision that Jon wrote the indexer was to provide visibility into forks of packages as well as the canonical version. Right now to do that you have to submit yourself to index.ros.org's special place to list forks: https://github.com/rosindex/rosforks/tree/master/repos

There's only two examples, conman and starmac there.  The vision was to have more of a crawler that would find forks and index them in automatically. It's much more ambitious than our current approach of relying on the rosdistro basically.

At the high level we could consider removing that ability. But that's a much more complicated cross cuting change. For now I'm just removing the extra generated pages and relying on the existing cross references which provide coverage of all the information already.


Right now for conman_msgs there are:
* https://index.ros.org/p/conman_msgs/github-jbohren-conman/#hydro
* https://index.ros.org/p/conman_msgs/#hydro
* https://index.ros.org/p/conman_msgs/github-RCPRG-ros-pkg-conman/#hydro
* https://index.ros.org/packages/conman_msgs/

For rclcpp:
* https://index.ros.org/p/rclcpp/github-ros2-rclcpp/
* https://index.ros.org/p/rclcpp/
* https://index.ros.org/packages/rclcpp/

After this change it will be: 
* https://index.ros.org/p/conman_msgs/github-jbohren-conman/#hydro
* https://index.ros.org/p/conman_msgs/#hydro
* https://index.ros.org/p/conman_msgs/github-RCPRG-ros-pkg-conman/#hydro

and 
* https://index.ros.org/p/rclcpp/
* https://index.ros.org/p/rclcpp/github-ros2-rclcpp/

I started trying to remove the second duplicate copy of all packages for the default repo such that the version in the first/default repository would not have a second copy. But that started getting complicated and I wanted to get this lower hanging fruit in.

This also can be done for the repositories in the same way as they have both cross references and list pages. If we were doing a REST api the lists make sense for completion, but that's not what we're presenting.

**Comment by clalancette** [comment]
OK, that's fine by me.  Thanks for the additional explanation.

**Review by clalancette — APPROVED** [review]

**Comment by tfoote** [comment]
This was confirmed to create ~7000 less pages https://build.ros.org/job/doc_rosindex/1205/ though it took very close to the same amount of time overall.

```
02:34:45.646 Filename                                                                                 | Count |       Bytes |    Time
02:34:45.646 _layouts/default.html                                                                    | 30522 | 2874956.98K |  65.428
vs
02:34:44.580 _layouts/default.html                                                                            | 23602 | 2795152.23K | 119.158
````
The removed pages can be seen being removed from the output repo in the log here: https://build.ros.org/job/doc_rosindex/1205/

**Pull request merged**
