### PR TITLE
Pr update versions

### PR DESCRIPTION
**Pull request by rkent**
This patch started with deleting Gemfile.lock, recreating, then fixing regressions. The Gemfile.lock update was done 2024-07-17 (or earlier, not sure). The additional commits are for regressions.

Biggest change is probably switching from redcarpet to kramdown for markdown. I did not try to understand the redcarpet options, and try to map them to kramdown, I just kept the existing kramdown configurations.

I've been running this for awhile at index.rosdabbler.com, and am not aware of any issues. But I really know very little about the ruby universe.

_plugins/redcarpet_toc.rb is misnamed, it does not require redcarpet, but I did not rename.

### CODE REVIEW

**Comment by tfoote** [comment]
This needs a rebase as it has a conflict in _config.yml

Fixes #307

**Comment by rkent** [comment]
Rebase completed.

**Review by tfoote — APPROVED** [review]
Thanks for this cleanup. Ruby's always a pain to update. 

I tested this out on my machine as well and it seemed to work. So we'll give it a try.

**Comment by tfoote** [comment]
Also as a side note I ran a build after this and the build time changed from 327 minutes elapsed to 247 minutes elapsed to build/ That's a 25% speedup!

image

The console log verbosity is way down 604122 vs 447902 lines of output. Most of those are likely are related to fixing #307

**Comment by rkent** [comment]
And all this time I though [you liked verbosity](https://github.com/ros-infrastructure/rosdoc2/pull/147)!

A lot of the rosindex verbosity comes from the --verbose option in the Makefile. I've removed that in my dev versions.

**Comment by tfoote** [comment]
I do like verbosity that communicates information ;) Repeated and redundant information is not helpful. I've trolled through a lot of logs and being able to find the information there is what's important especially for things like this that are very hard to reproduce.

**Pull request merged**
