### PR TITLE
Combined search/list deps page

### PR DESCRIPTION
**Pull request by rkent**
This adds a tabulator-based combined list and search page for system dependencies. Much of this is a copy of what we did with the package list page. This does not show this new page in the UI (like with package list), to view it you need to enter `/search_deps/`

It adds additional fields to deps, allow searching by upstream package name, platform, ROS package dependant, in addition to dep name and description. I'm not sure system dependency search needs all of this, but it was not difficult to add.

This removes the sharding from the search data for deps, which also affects the existing search page. The size still seems managable. It will eventually be smaller once we remove the old search pages, as there is a lot of extraneous information in the data and index that was used by the old search page, but is not needed by the new one.

Although largely copied from the new package search page, there are two new features here that I also intend to add to the package search: initial sort by search score, and an extensive help page.

Our power is out which affects my build farm, so I am unable to run a non-development build with this for demo, but I will do that as soon as the power is restored.

### CODE REVIEW

**Comment by rkent** [comment]
Sorry for the revision, I discovered some unneeded code to remove.

**Comment by rkent** [comment]
Oops, sorry again for the redo, had to remove some spaces from blank lines.

**Comment by tfoote** [comment]
Thanks this sounds like a good step forward. @rkent Did you have a chance to run a test build for this?

**Comment by rkent** [comment]
Yes, this can be seen at https://index.rosdabbler.com/search_deps/  The 'search_deps' is not enabled in the UI, you need to enter it directly like this.

**Comment by rkent** [comment]
@tfoote is there something I can do to move this forward? I can't really expose the new package search until this is also landed.

**Review by tfoote — APPROVED** [review]
Thanks sorry it was a very busy week.

**Pull request merged**
