### PR TITLE
Add Contribution Suggestions Page

### PR DESCRIPTION
**Pull request by max-krichenbauer**
This PR proposes adding a new page that displays open issues and PRs
so that people who are looking for place to contribute can easily find one.

image

Please let me know what you think.

### CODE REVIEW

**Comment by itualami** [comment]
Great work! Do you think, we should add "priority" to the information displayed. It could have these values (High, Medium, and Low). But, I'm not sure where to source this information from?

**Comment by dirk-thomas** [comment]
Can you please describe the general idea. Atm it seems to just enumerate all open issues and pull requests which doesn't seem like a good list for "Suggestions ... where Contributors are needed".

**Comment by itualami** [comment]
> Can you please describe the general idea. Atm it seems to just enumerate all open issues and pull requests which doesn't seem like a good list for "Suggestions ... where Contributors are needed".

We intent to use this page as a reference to promote code review. It will be the source of truth for PRs waiting for review. We will promote it in Twitter, ROS Discourse, etc. This is a problem in the ROS community, high number of PRs being unreviewed.

We hoping by promoting this page, we will get more reviewers for the pending PRs. However, I believe we need more information in the report. For example, priority (i.e. the urgency to review the PR) would be good, how friendly is it for newcomers, author, status (e.g. ready for review), ...

**Comment by max-krichenbauer** [comment]
Sorry for the late reply.

Thank you @dirk-thomas  and @itualami for your comments.

I have updated the PR to filter suggestions based on labels (tags) of the respective issue or PR.
Of course, labels can be arbitrarily chosen by the maintainer, but looking around a bit I found these following labels usually indicate that an issue invites contributions:
```
    'help wanted'       => 10,
    'review requested'  => 10,
    'good first issue'  => 10,
    'needs discussion'  =>  5,
    'task'              =>  5,
    'more work needed'  =>  5,
    'documentation'     =>  3,
    'bug'               =>  2,
    'minor'             =>  2,
    'major'             =>  1,
    'enhancement'       =>  1
```
The last 5 entries in themselves don't indicate that an issue invites contributions, but is instead used to prioritize between those who do. Meaning that 'help wanted' on a 'documentation' issue will be listed higher than on a 'enhancement' issue.
So only issues with a minimum priority of 5 are displayed on the list.

A positive side effect of this system would be that it encourages maintainers to use standard labeling to invite contributions.

Please let me know what you think.

**Comment by itualami** [comment]
> Sorry for the late reply.
> 
> Thank you @dirk-thomas and @itualami for your comments.
> 
> I have updated the PR to filter suggestions based on labels (tags) of the respective issue or PR.
> Of course, labels can be arbitrarily chosen by the maintainer, but looking around a bit I found these following labels usually indicate that an issue invites contributions:
> 
> ```
>     'help wanted'       => 10,
>     'review requested'  => 10,
>     'good first issue'  => 10,
>     'needs discussion'  =>  5,
>     'task'              =>  5,
>     'more work needed'  =>  5,
>     'documentation'     =>  3,
>     'bug'               =>  2,
>     'minor'             =>  2,
>     'major'             =>  1,
>     'enhancement'       =>  1
> ```
> 
> The last 5 entries in themselves don't indicate that an issue invites contributions, but is instead used to prioritize between those who do. Meaning that 'help wanted' on a 'documentation' issue will be listed higher than on a 'enhancement' issue.
> So only issues with a minimum priority of 5 are displayed on the list.
> 
> A positive side effect of this system would be that it encourages maintainers to use standard labeling to invite contributions.
> 
> Please let me know what you think.

I like the idea of the filter. Given these values, they do not reflect a priority but rather additional information for the user. I suggest to name the filter Additional Information?

**Comment by max-krichenbauer** [comment]
@itualami Thank you for the comment.
I agree that "Priority" is misleading here, but I feel that "Additional Information" is too vague.
I was looking for a word that describes how "welcome" and "possible" a contribution would be.
Here are some other suggestions:

- "need"
- "recommendation"
- "demand" (maybe sounds a bit harsh)

We could also just replace the name with a logo (like a [star](https://fontawesome.com/v4.7.0/icon/star) or a [thermometer](https://fontawesome.com/v4.7.0/icon/thermometer-three-quarters)) that expresses the idea more abstractly than a word.

**Comment by itualami** [comment]
> @itualami Thank you for the comment.
> I agree that "Priority" is misleading here, but I feel that "Additional Information" is too vague.
> I was looking for a word that describes how "welcome" and "possible" a contribution would be.
> Here are some other suggestions:
> 
> * "need"
> * "recommendation"
> * "demand" (maybe sounds a bit harsh)
> 
> We could also just replace the name with a logo (like a [star](https://fontawesome.com/v4.7.0/icon/star) or a [thermometer](https://fontawesome.com/v4.7.0/icon/thermometer-three-quarters)) that expresses the idea more abstractly than a word.

These labels are provided by the maintainers. If so, we should be explicit about it. Hence, these are my recommendations:

1. Maintainer's Need
2. Maintainer's requirement
3. Maintainer's comment

Thanks

**Comment by max-krichenbauer** [comment]
Thank you for the suggestions. I agree, but I feel that it's hard to capture the meaning in just one or two words adequately, and the column is getting too wide for just a simple number.
So here is my suggestion:
just display an icon and add a hover-over explanation of what the rating means:

image

**Comment by gavanderhoorn** [comment]
I like the idea in general, but from the screenshots shown it's unclear to me whether this is per repository or package, or a global listing of *all* open issues and PRs across *all* indexed repositories.

It's been said that having too much information is not good, just as having no information.

Seeing as the index currently scraptes 2000+ repositories, a list of everything would not be meaningful.

**Comment by max-krichenbauer** [comment]
@gavanderhoorn As mentioned in the text (first post firs sentence),
this page displays open issues and PRs. So one line per issue / PR.
And as mentioned in the next post: only issues / PRs that have some kind of 'help wanted' tag attached to them.

**Comment by gavanderhoorn** [comment]
> this page displays open issues and PRs. So one line per issue / PR.

yes, but does it only display the issues/PRs for a single repository, or for all indexed repositories?

The difference would be showing issues and PRs of 2000+ repositories in a single list versus having a per-repository list.

**Comment by max-krichenbauer** [comment]
Ah, now I understand what you mean.
Currently it displays all issues/PRs for all repos - as long as they are tagged sufficiently.
I don't know how many that would be. Currently it seems most repos don't use the tags a lot, and those who do usually only have 1-2 "help wanted" or "review requested" PRs open at a time.

**Comment by gavanderhoorn** [comment]
It might be good to consider what will happen when maintainers do start tagging issues like that -- say because of some event that asks them to do that (a hackathon or similar).

Even if -- across 2000 repositories -- only 1 issue or PR gets the label, that means a list of over 2000 elements.

That seems like it would be too much.

**Comment by max-krichenbauer** [comment]
I do understand what you mean, but as it is, the repository list page itself is 2000 long, the package list page even longer. Why could this page not be similar in length and how would you suggest to shorten it without unfairly penalizing some?

EDIT: Also maybe we should move the discussion to Discourse so others can join.

**Comment by gavanderhoorn** [comment]
> the repository list page itself is 2000 long, the package list page even longer. Why could this page not be similar in length

I feel those pages have a different purpose: both the package and repository list are there to be searched through, and I don't believe people will just browse them.

The list that you are proposing is supposed to engage (new) people. They will probably not browse the list either. It's supposed to offer "a way in" or entry-point. Listing everything that is there is probably going to be overwhelming.

Where would they start? Top of the list? A random entry? Are there ways to filter the list? If not, could we add that? If we do: what would they filter on?

In the end, if engaging people is the idea, a very long list might not be the best way to do that.

> how would you suggest to shorten it without unfairly penalizing some?

It might be an idea to list outstanding issues and PRs on the per-package pages as a tab (next to the `Q&A` tab perhaps).

Another option could be to aggregate the nr of issues and PRs labelled `help wanted` and show a ranking based on that. That could give an indication where help is most wanted. Same for issues labelled `good first issue` (or similar): that could show which repositories could be good starting points for newcomers.

> EDIT: Also maybe we should move the discussion to Discourse so others can join.

Having this discussion here makes sense as it debates the exact changes that are proposed. The Discourse post was intended to draw attention to the PR.

**Comment by max-krichenbauer** [comment]
>Where would they start? Top of the list? A random entry?

Yeah, why not? People can browse around a bit at the top and pick one.
Google search usually offers millions of results for any keyword.
People aren't overwhelmed by that. They browse the first page, maybe the second page too and pick what appears best.
So to me this is like Googleing: "where in ROS is my help wanted" and getting 2000 results.

> Are there ways to filter the list? If not, could we add that? If we do: what would they filter on?

People can already sort by the language (Python or C++) and whether it's an Issue or a PR.
More filtering might be implemented, but I'm not sure how well the current system or `rosindex` would support that.

> It might be an idea to list outstanding issues and PRs on the per-package pages as a tab (next to the `Q&A` tab perhaps).

Sorry I don't understand the reasoning behind your suggestion.
The way I understand you, the following would happen:

**Me:** I want to help somewhere. Where do I start?
**index.ros.org:** Open issues are listed on the individual package pages.
**Me:** Okay, which packages are there?
**index.ros.org:** Here is a 2000 item long list of packages. You can start at the top or a random package as there is no way to filter them.
**Me:** Okay, how about package X?
**index.ros.org:** This package does not have open issues with 'help wanted' tag.
**Me:** Okay, how about package Y?
**index.ros.org:** This package does not have open issues with 'help wanted' tag.
**Me:** Okay, how about package Z?
**index.ros.org:** This package does not have open issues with 'help wanted' tag.
and so on until I randomly find a package that has a suitable issue or rather I just give up.

> Another option could be to aggregate the nr of issues and PRs labelled `help wanted` and show a ranking based on that. That could give an indication where help is most wanted. Same for issues labelled `good first issue` (or similar): that could show which repositories could be good starting points for newcomers.

In my experience, having many open issues or PRs rather reflect the size and/or much of a central point of the infrastructure a project is, not how well it is suited for beginners to contribute.
If you're just starting out, trying to contribute to a huge or infrastructure-critical project with a strict review process is rather demotivating.

**Comment by gavanderhoorn** [comment]
I's rarely the case that people new to a community do not have an area or topic which interests them.

Being able to filter a list of issues by that would probably help them find something they'd *want* to work on, instead of showing them everything they *could* work on.

But perhaps it would be good to ask for some input from someone who has done research into community management and perceptions of outsiders.

@itualami: would you add something here?

> In my experience, having many open issues or PRs rather reflect the size and/or much of a central point of the infrastructure a project is, not how well it is suited for beginners to contribute.
> If you're just starting out, trying to contribute to a huge or infrastructure-critical project with a strict review process is rather demotivating.

Github has a label specifically for issues that are good issues for newcomers to start with: [Helping new contributors find your project with labels](https://help.github.com/en/github/building-a-strong-community/helping-new-contributors-find-your-project-with-labels).

**Comment by itualami** [comment]
> I's rarely the case that people new to a community do not have an area or topic that interests them.
> 
> Being able to filter a list of issues by that would probably help them find something they'd _want_ to work in, instead of showing them everything they _could_ work on.
> 
> But perhaps it would be good to ask for some input from someone who has done some research into community management and perceptions of outsiders.
> 
> @itualami: would you add something here?
> 
> > In my experience, having many open issues or PRs rather reflect the size and/or much of a central point of the infrastructure a project is, not how well it is suited for beginners to contribute.
> > If you're just starting out, trying to contribute to a huge or infrastructure-critical project with a strict review process is rather demotivating.
> 
> Github has a label specifically for issues that are good issues for newcomers to start with: [Helping new contributors find your project with labels](https://help.github.com/en/github/building-a-strong-community/helping-new-contributors-find-your-project-with-labels).

Communities which are newcomers friendly are usually sustainable and attract an ongoing flow of newcomers. Unfortunately, that’s not the case of ROS. It has high entry barriers (e.g. complexity of robotics).

If the overall intent of this initiative is to attract contributions (e.g. code review), then we should focus primarily on attracting newcomers. They are usually the ones with time, eagerness to contribute, but they need guidance. I’ve noticed that other communities leverage this enthusiasm to convert newcomers to ongoing contributors.

To make my argument short, I concur with @gavanderhoorn 

This is an example of how, a newcomers friendly community, labels its [issues](https://github.com/coala/coala/issues).

**Comment by max-krichenbauer** [comment]
@gavanderhoorn 

> I's rarely the case that people new to a community do not have an area or topic which interests them.

Sorry, now I understand your argument for a list of packages, ranked by how many "help-wanted" issues they have even less.
If ROS newcomers know from the start in on what package they want to work on, why have a list of packages with many "help-wanted" issues?

> Github has a label specifically for issues that are good issues for newcomers to start with: [Helping new contributors find your project with labels](https://help.github.com/en/github/building-a-strong-community/helping-new-contributors-find-your-project-with-labels).

Yes, this is exactly one of the labels that the list is currently being filtered on. Please see my [previous message](https://github.com/ros-infrastructure/rosindex/pull/194#issuecomment-560200439)

**Comment by max-krichenbauer** [comment]
@itualami 

> To make my argument short, I concur with @gavanderhoorn

Sorry, I don't understand in what point you concur with him.
Do you concur with him that ROS newcomers usually already have a package in mind that they want to work on and don't need a central page?

> This is an example of how, a newcomers friendly community, labels its issues.

I can make the list respect those labels as well in it's ranking, but until maintainers start placing these labels, should we not just use "help wanted", "good first issue" and "review requested" as indicators? These are already sometimes used in ROS.

**Comment by itualami** [comment]
I meant, I agree with this "Being able to filter a list of issues by that would probably help them find something they'd want to work on, instead of showing them everything they could work on."

**Comment by max-krichenbauer** [comment]
> 
> 
> I meant, I agree with this "Being able to filter a list of issues by that would probably help them find something they'd want to work on, instead of showing them everything they could work on."

Sorry, I still don't really understand. Could you give an example please for such a filter?

**Comment by itualami** [comment]
> > I meant, I agree with this "Being able to filter a list of issues by that would probably help them find something they'd want to work on, instead of showing them everything they could work on."
> 
> Sorry, I still don't really understand. Could you give an example please for such a filter?

I was thinking to create a filter for these values and hopefully in the future the value supplied by the maintainers will more significant. Then newcomers can filter "good first issue", to find issue suitable for a beginner.

    'help wanted'          => 10,
    'review requested'  => 10,
    'good first issue'     => 10,
    'needs discussion'  =>  5,
    'task'                        =>  5,
    'more work needed'  =>  5,
    'documentation'       =>  3,
    'bug'                          =>  2,
    'minor'                       =>  2,
    'major'                        =>  1,
    'enhancement'           =>  1

**Comment by max-krichenbauer** [comment]
But these are already the labels that the list is filtered by.
If a PR has neither the 'help wanted', 'review requested' or 'good first issue' label, it won't be in the list.

I can offer making separate pages, one for 'review requested' and one 'good first issue'.

**Comment by itualami** [comment]
> But these are already the labels that the list is filtered by.
> If a PR has neither the 'help wanted', 'review requested' or 'good first issue' label, it won't be in the list.
> 
> I can offer making separate pages, one for 'review requested' and one 'good first issue'.

I understand now. I like the idea of splitting into 3 pages based on the labels. This would allow us to target the right audience with the right links.

**Comment by max-krichenbauer** [comment]
Okay, I split the contribution suggestions into three different lists. One for 'help wanted' one for 'good first issue' and one for 'review requested'.

**Comment by itualami** [comment]
> Okay, I split the contribution suggestions into three different lists. One for 'help wanted' one for 'good first issue' and one for 'review requested'.

Excellent! good work.

**Comment by tfoote** [comment]
I like the split into separate displays to show the three different categories.

Thinking a little bit deeper I think that it makes a lot more sense to show these lists under the repository pages not a top level page. Ever subproject has it's own expertise areas and processes and without homogeneity will end up with very different experiences for people connecting. Enforcing homogenization on all of them, while admirable in thought is not possible and kind of goes against the sprit of the larger federated model that the ROS ecosystem works on.

To that end I'd like to propose an alternative approach. Each repository page can determine if there's a CONTRIBUTING.md and if so render that into the repository page. And next to that it will render the three highlighted lists of issues discussed above. 

I'd also like to see the content be more dynamic using the APIs for the issues in the browser instead of at crawl time. If the queries are only loaded when the Contributing tab is opened on the appropriate repository page we shouldn't hit rate limit issues. Building all this content into rosindex crawl has significant scale and update rate implications. The index is likely not going to be updated more than once daily, and if we get better at things it likely will be less often waiting for changes before reindexing which won't necessarily capture changes on issues which can be much more dynamic than the package metadata.

For the above issue of understanding how to get involved and find a project to contribute to. I would suggest that the list of projects that are best for new contributors to learn and also specifically for areas of interest with receptive development processes be manually maintained. Through the manual maintence of this list projects can be vetted and feedback provided. As well as context and explainations can be added to help the new users. The number of tags, on a project or any other automated heuristic will never capture the sort of things that really matter to new developers. For example I could add 'good-first-issue' to an issue on my repositories but I may be expecting this to be an expert in the field already, whereas another project may put `good-first-issue` tags on things that someone could dig into during their first internship or programming class. It's highly context dependent.

The content could easily be an additional section on this sort of page: https://wiki.ros.org/Get%20Involved

**Comment by max-krichenbauer** [comment]
@tfoote Thank you for the feedback!

Please let me know if I understand you correctly:

(1) The contribution suggestions should be shown on the page of each package, like in this mock-up screenshot:
image

(2) They should still be split into three lists: 'help wanted', 'good first issue' and 'review requested'.

(3) The lists should be populated via JavaScript by the browser (similar to the Q&A section), not by index itself.

(4) The list / tab should only be displayed if the repository has a `CONTRIBUTING.md` file on the repository.

(5) The global (current) lists should be replaced with a hard-coded, hand-maintained list of packages, which are considered good starting points for newcomers.

Is that correct?

**Comment by tfoote** [comment]
Overall yes, here's a few clarifications. 

1) I think that we can't easily associate the issues to the packages themselves. The issues are typically on the repositories so I'd put the (tab) or main view on the repositories page. 

In that tab I'd suggest having the Contributing.md rendered at the top and then the three lists below. 

To keep visibility on the package page a link in the "Repository Summary" section to the effect of "How to contribute to this repository" with a link to the above contributions tab would be the best. To be super fancy it could have three conditional links to the "help wanted" "good first issue" and "review requested" lists which would show the counts of each of those lists if non-zero. 

2) Yes. Though I might consider changing "review requested" to be "Open Pull Requests" since review requests are generally directed to an individual, and any open PR is fair game to review.

**Comment by max-krichenbauer** [comment]
Thank you!
I started working on it in a new branch over at https://github.com/esol-community/rosindex/tree/ros2_contributing_info for simplicity (can merge it back into this PR later).

Here's a first screenshot - the new box is displayed on the repo's page below the "README" section.
image
As you can see, the list currently has no columns, because I'm not sure what columns it should have.
- The "Pull Request or Issue" column doesn't make sense if anymore if the lists are separated.
- The "Repository" column doesn't make sense anymore since we're already on the repo page.
- The "Language" column was based on repo info and thus also doesn't make sense anymore.

This only leaves the "Date created" column, which I'm not sure if it's interesting at all.
Are there any columns the list should have?

**Comment by max-krichenbauer** [comment]
Here's a screenshot of the links on each package page:
image
Each of those labels links directly to the respective list on the repo page.

**Comment by max-krichenbauer** [comment]
I merged the other branch for easier code review and also added the hard-coded suggestion page:

image
The buttons link to the respective list on the repo's page and the numbers are again queried with JavaScript.

Please let me know what you think.

**Comment by max-krichenbauer** [comment]
The suggested repos for the list are now set in the `_config.yml`, and I improved the list a bit:
the last commit time is now being displayed and people can sort the list by it.
image

**Comment by tfoote** [comment]
> This only leaves the "Date created" column, which I'm not sure if it's interesting at all.
Are there any columns the list should have?

I think having the issue/PR number listed would be valuable as that's what people usually reference for shorthand. It could be a column or just a whitespace separated print before the title.

Having the repositories listed in the _config.yaml is good. That makes it relatively clear where to add them. It might make sense to give a pointer somewhere on the page to direct pull requests there though. "If you maintain a repository and would like to be listed here. Please open a PR to be added <to this list>"

And can we add at the top of the Contributions Suggestions page a paragraph to the effect of:

> The following repositories have indicated that they're looking for new contributors and have setup some helpful tags on issues that they hope will be good entry points. Below are links to the issues in their trackers.

Maybe it would make sense to append the above link how to contribute to that paragraph too.

**Comment by max-krichenbauer** [comment]
Thanks for the feedback.

Here is is updated issues list:
image

And here is the updated contribution page:
image
The `_config.yml` text part is also a hyperlink to the github repository of `rosindex`, pointing directly at the `_config.yml` file.

**Review by tfoote — APPROVED** [review]
Thanks for fleshing this out. It will definitely be more welcoming.

**Comment by max-krichenbauer** [comment]
Thank you!

**Comment by itualami** [comment]
Great work! I'd like to thank everybody involved, especially @max-krichenbauer  and @tfoote.

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/next-ros-quality-assurance-working-group-february-2020/12571/1

**Pull request merged**
