### PR TITLE
Re-enables lunr.js

### PR DESCRIPTION
**Pull request by hidmic**
Connected to #28. This pull request brings back `lunr.js`, along with client-side pagination (which was missing), and effectively deprecates GCSE usage. It also updates `lunr.js` itself, from 0.5.6 to 2.3.3. It seems to be slightly faster to index. It remains to be seen how it'll perform once served and how well it will deal with a larger dataset (e.g. ROS and ROS 2 packages combined). 

search_lunr

**A note of warning**. At some point in time, `rosindex` maintainer introduced this [`vuvuzela`](https://www.npmjs.com/package/vuvuzela) node module to serialize the index in a non-recursive way. I presume he was having issues with the size of the index (though I don't know for a fact). However, said module won't work with `lunr.js`, as it implements custom [`toJSON()`](https://javascript.info/json#custom-tojson) methods for its classes. So if size ever becomes an issue later on, we'll need to figure out how to work around it in some other way.

### CODE REVIEW

**Comment by hidmic** [comment]
Note to the reviewers: focus on 04a4013794ae54d7b6fd7bb45f47b640152a0f92. The other commit just changes `lunr.js` version and adapts the index builder node tool to work with it.

**Review by tfoote — APPROVED** [review]
It certainly works well locally.

image

Lets see how it does when deployed. The search does not appear to be the slowest part of the page load yet.

Would it make sense for us to roll back vuvusela if we aren't seeing the performance needs right now since it's less standard and unmaintained for 2 years?

**Comment by hidmic** [comment]
@tfoote it makes sense to me, but I didn't want to drop it just yet. At least not before checking with you guys. 

We should deploy this and check how it goes :)

**Comment by hidmic** [comment]
Alright, going in.

**Pull request merged**
