### PR TITLE
Improves documentation navigability

### LINKED ISSUE #122: index of all pages
By @dirk-thomas in https://github.com/ros-infrastructure/index.ros.org/issues/1

It would be good to generate an index of all the available pages under e.g. https://index.ros.org/doc/ros2/

Currently I find myself going to the old GitHub wiki which has that index and then following the link to index.ros.org.

### PR DESCRIPTION
**Pull request by hidmic**
Closes #122 and an improvement on top of #65. This pull request improves documentation pages navigability by means of an index and better breadcrumbs at the top. End result using https://github.com/ros2/ros2_documentation/pull/79 is shown below:

rosindex_docs_index

I'm very much open to style suggestions, I'm not that good with CSS.

Depends on #118.

### CODE REVIEW

**Comment by chapulina** [comment]
This is looking generally good to me, putting the pages in a hierarchy is a great idea!

Some initial comments on the usability:

1. After selecting a page, the whole menu collapses to the initial state, which can be off-putting. Not sure how hard it would be to keep the menu's state, given that new pages are being loaded once you pick them. Maybe we can at least make sure to expand the menu to show the current page?
1. Clicking on the ellipsis expands the content, but there's no way to collapse it back, which was a bit unexpected to me. A few times, I clicked on a top-level item expecting it to collapse its children, when it just loaded the page and the menu "disappeared" (due to comment 1)
1. In fact, the whole ellipsis concept is something I was not familiar with. I have a feeling that collapsible menus usually work like the one [here](https://idratherbewriting.com/documentation-theme-jekyll/), with icons to clearly show a collapsible's state.
1. This is probably out of the scope of this PR, but a filter would be fantastic!
    **User story**: I want to find documentation on how to bloom a package. I go to the main page and `Ctrl+F` "bloom" - no hits. I click on the ellipsis to expand the menu, many more pages show, then I `Ctrl+F` "bloom" again - no hits. I need to keep "semi-randomly" clicking on ellipses until my `Ctrl+F` has a hit. With a filter similar to the one on the Github wiki, it would be straightforward to get to the bloom page. An alternative would be to address https://github.com/ros-infrastructure/rosindex/issues/113.

**Comment by hidmic** [comment]
Thanks for all the feedback @chapulina !

1. Expanding up to the current page would be the simplest solution. Keeping menu state across pages is somewhat trickier, there isn't even a state representation but the state the DOM carries. But I guess we can use cookies or some other local mechanism to do that if we want that too.

2. (& 3) Right. The rationale was that the lookup process is one way: one goes deep into the hierarchy and once the right document has been found there's no need to keep the hierarchy around anymore. Also, the top level items may (and currently do, after ros2/ros2_documentation#79) link to other pages too. But we can replace those ellipsis (which are a simple variation on what Github provides in wikis) by some other handle that allows collapsing as well. I don't have a strong opinion on this regard.

4. Hmm I think it's doable. But as you said, now #130 brings in some of that functionality. Both features (i.e. content searching and index filtering) can coexist though, so I believe it's a matter of whether we want a minimalist and straightforward UI or one with lots of knobs that the user can choose from.

**Comment by hidmic** [comment]
Alright, I propose we:

1. Expand the hierarchy up to the current page.
2. Replace all ellipsis by handles to expand and collapse back.
3. Rely on #130 for page filtering.

I think it's a reasonable trade-off between implementation effort and feature usefulness. @chapulina what do you think?

**Comment by hidmic** [comment]
Alright, https://github.com/ros-infrastructure/rosindex/pull/129/commits/419c8c5a9c560ad32c00c7d2a1c87b736a072f45 implements above features. PTAL!

**Comment by hidmic** [comment]
Any other comments on this one?

**Comment by apojomovsky** [comment]
Not completely sure if this is the intended behavior but I'm getting the "This page now lives here" message while accessing some of the items from the index. Should we update those links?
screenshot from 2019-01-07 15-45-21

**Comment by hidmic** [comment]
Hmm it's not intended but expected. The index includes all pages, even those that are there only for backwards compatibility purposes...

I'll add a blacklisting feature to the documentation generation plugin so that we can get rid of those. Thanks for the review @apojomovsky !

**Comment by hidmic** [comment]
@apojomovsky Alright, https://github.com/ros-infrastructure/rosindex/pull/129/commits/cbadbe8019639a355a88bdcbb475da60bc51fc4e adds support for a `rosindex.yml` file at each documentation repository root to specify sources location and glob patterns to limit the collection of pages being indexed (all pages are rendered, some will not show up in the index nor in search results). Default behavior when said file is not present is the same as it used to be.

**Review by apojomovsky — APPROVED** [review]
Thanks for addressing my comment @hidmic !
Just tested your changes (along with https://github.com/ros2/ros2_documentation/pull/89) and worked as expected, it LGTM.

**Comment by hidmic** [comment]
Alright, thanks for the all the feedback! I'll move on and merge this one. We can follow-up if more usability concerns show up at https://index.ros.org.

**Pull request merged**
