### PR TITLE
Add checks for querying remote end points in case of network errors.

### PR DESCRIPTION
**Pull request by tfoote**

### CODE REVIEW

**Comment by tfoote** [comment]
@rkent if you could confirm this works for you that would be great. I ran into it when running locally when the network config changed while this was running in the background.

**Comment by rkent** [comment]
Trying to figure out if "this works for you" I was trying to understand why I was not seeing the Continuous Integration text in the UI. Turns out this is a regressions from my #417.  `package_qna_updates.html` was not using `prettify.css` and `prettify.js` (so I deleted their reference and files). Turns out that prettify.css IS used in package_instance.html for the CI stuff. It got moved into package_qna_updates.html at some point, but that is included in the package_instance.html where the CSS is actually needed.

So I'm quite sure how to interpret "this works for you" since it doesn't, but not the fault of this PR. I think I'll fix the prettify.css issues, then try the current PR on top of that.

**Comment by tfoote** [comment]
I was only fixing the build crashing, not checking the output rendering. Without these catches, I wasn't able to get through the scanning process on my dev machine due to network changes happening periodically on my host. So if the build passes I'd consider this to work for you.

**Review by rkent — APPROVED** [review]
LGTM.

I simulated the error by adding a fake `docs.ros.org` to `etc/hosts` and it continued cleanly, generating the new error messages.

**Pull request merged**
