### PR TITLE
Rosdep path

### PR DESCRIPTION
**Pull request by tfoote**
Add support for using an alternative rosdep source than the rosdistro being indexed.

### CODE REVIEW

**Comment by dhood** [comment]
did we want to add a rosdep submodule too?

**Comment by tfoote** [comment]
No, I've been working to clear out the submodules in #8 so we don't have content in our source trees.

**Comment by hidmic** [comment]
@tfoote superseded by #8?

**Comment by hidmic** [comment]
Indeed it was superseded. Closing.

**Pull request closed without merging**
