### PR TITLE
Extends searching capabilities

### LINKED ISSUE #113: search results incomplete
I tried to search for `ROS_DOMAIN_ID` but the result list is empty even though there are multiple pages containing that term.

* https://index.ros.org/doc/ros2/Linux-Development-Setup/#multiple-host-interference
* https://index.ros.org/doc/ros2/Overview-of-ROS-2-concepts/#discovery
* https://index.ros.org/doc/ros2/ROS-2-On-boarding-Guide/#choose-a-dds-domain-id
* https://index.ros.org/doc/ros2/Set-up-a-new-macOS-CI-node/#ros-2-ci-host-setup

### PR DESCRIPTION
**Pull request by hidmic**
This pull request extends searching capabilities to system dependencies and documentation pages, as shown in the demo below:

search_demo

Further validation and adjustment will likely be required once deployed, given that the search index size has increased and it is known this has non negligible effects on usability.

Closes #113, #101 and partially deals with #71. Builds on top of #129 and thus it should be merged afterwards.

### CODE REVIEW

**Comment by hidmic** [comment]
Same as for #129, this could use some real UI design work.

**Comment by hidmic** [comment]
@dirk-thomas mind to take a look? I think it was you who opened #113. Mostly looking for feedback on usability.

**Comment by dirk-thomas** [comment]
If it enables to search for content in the ROS 2 docs as shown in the animation than :+1: from me.

I haven't build the inde page locally to try the usability of it.

**Review by apojomovsky — APPROVED** [review]
Just built it locally and verified the new functionality to work as expected so this LGTM

**Comment by hidmic** [comment]
This one could use another look too.

**Comment by hidmic** [comment]
@apojomovsky if you have time, would you mind giving this one a try?

**Comment by apojomovsky** [comment]
Re-tested with the latest changes and it worked as expected :thumbsup:

**Comment by hidmic** [comment]
OK, there's one more aspect of this that hasn't been covered by tests performed so far. We don't know what the latency for searching is going to be, considering that the amount of data we have to download has increased. 

If we don't want to test that in production (I'd think not), we can bring a test farm back on and push results to a dummy site repo fork (I'm not proposing a local build because it takes ages just to download on our end). Thoughts @chapulina @tfoote @apojomovsky? Would that be possible @nuclearsandwich ?

**Comment by nuclearsandwich** [comment]
> Thoughts @chapulina @tfoote @apojomovsky? Would that be possible @nuclearsandwich ?

I didn't feel like spinning up a three-machine testfarm just for this one. I've started a build locally from HQ where bandwidth is at least reasonable and it's getting toward the end of the day. I should get a ping on my phone when it completes and I'll publish it to a random url for inspection.

**Comment by nuclearsandwich** [comment]
I merged this branch into master, ran a build and deployed the site to http://rosindex.nuclearsandwich.com when I try to use search there I don't see the documentation search results area.. Did I miss a step?

edited for clarity.

**Comment by hidmic** [comment]
@nuclearsandwich there's no documentation search bar. There's the search bar.

Just tried it out. It works, but it takes 3 to 5 seconds to show anything :/

**Comment by nuclearsandwich** [comment]
> Just tried it out. It works, but it takes 3 to 5 seconds to show anything :/

Maybe I just wasn't waiting long enough for it to appear then.

**Comment by nuclearsandwich** [comment]
> documentation search bar. There's the search bar.

Sorry. Apparently a bit of morning dysphasia. By search bar I meant search results area.

If I actually wait for it, the results do show up.

**Comment by hidmic** [comment]
@nuclearsandwich no worries! :) 

@chapulina @tfoote could you also take a look? I'm not sure we can do better than this by more shards per index. I guess we could make the user to be specific about where to look.

**Comment by chapulina** [comment]
One idea to improve performance is to only perform the search for one type of page at first, and have links for the other types in the result.

For example, on Github, when you [search](https://github.com/search?q=banana) it first shows only results for "Repositories". You need to click on the menu on the left to show other types of results, like "Code", "Commits", etc.

**Comment by hidmic** [comment]
I see. Alright then, I'll try to get back to this before the end of this week and tweak the UI to use at most one index at a time.

**Comment by hidmic** [comment]
Alright, I've refactored the UI somewhat to show one kind of search results at a time. It works by dynamically adjusting the priority of each AJAX request, meaning we download them all anyways but in an order that minimizes the UI delay from a user perspective. @chapulina mind to take a look? @nuclearsandwich may I ask you to re-deploy it to check download latency?

**Comment by hidmic** [comment]
Just for the record, it was a pain to add this. Developing features like these in `rosindex` makes me wonder if we'd be better off with a ~better~ supporting framework below us instead.

**Comment by nuclearsandwich** [comment]
Deployed to http://hidmic.rosindex.qux.sh/

**Comment by hidmic** [comment]
Ok, I just got to fix one small detail to have a decent UX. 

About latency, it's better, but not **that** much better. The lunr index is huge, period.

**Comment by chapulina** [comment]
I didn't look at the code, but the deployed result looks good to me!

I just noticed one small detail, not sure if that's what you're working on, but when I click on a new tab in the search results, the `section` on the URL doesn't change. It seems to only change when I perform a search from the `/search` page itself.

**Comment by hidmic** [comment]
Our minds our connected. Or that's so awful it stands out, not sure.

**Comment by hidmic** [comment]
@chapulina done, PTAL! It's not the prettiest code ever but it works.

**Review by chapulina — APPROVED** [review]

**Comment by hidmic** [comment]
Ok I'm going in with this one. We can revert if things get out of hand in terms of search latency.

**Pull request merged**
