### PR TITLE
Add nil check for img alt attribute.

### PR DESCRIPTION
**Pull request by nuclearsandwich**
Resolves:
```
    /tmp/doc_repository/_ruby_libs/text_rendering.rb:27:in `rescue in block in fix_local_links': undefined method `empty?' for nil:NilClass (NoMethodError)
        from /tmp/doc_repository/_ruby_libs/text_rendering.rb:20:in `block in fix_local_links'
        from /home/jenkins-agent/.bundle/gems/nokogiri-1.8.5/lib/nokogiri/xml/node_set.rb:204:in `block in each'
        from /home/jenkins-agent/.bundle/gems/nokogiri-1.8.5/lib/nokogiri/xml/node_set.rb:203:in `upto'
        from /home/jenkins-agent/.bundle/gems/nokogiri-1.8.5/lib/nokogiri/xml/node_set.rb:203:in `each'
        from /tmp/doc_repository/_ruby_libs/text_rendering.rb:19:in `fix_local_links'
        from /tmp/doc_repository/_ruby_libs/text_rendering.rb:96:in `get_md_rst_txt'
        from /tmp/doc_repository/_plugins/rosindex_generator.rb:38:in `get_readme'
        from /tmp/doc_repository/_plugins/rosindex_generator.rb:475:in `scrape_version'
        from /tmp/doc_repository/_plugins/rosindex_generator.rb:570:in `block in scrape_repo'
        from /tmp/doc_repository/_plugins/rosindex_generator.rb:539:in `each'
        from /tmp/doc_repository/_plugins/rosindex_generator.rb:539:in `scrape_repo'
        from /tmp/doc_repository/_plugins/rosindex_generator.rb:1207:in `block in generate'
        from /tmp/doc_repository/_plugins/rosindex_generator.rb:1201:in `each'
        from /tmp/doc_repository/_plugins/rosindex_generator.rb:1201:in `generate'
        from /home/jenkins-agent/.bundle/gems/jekyll-3.8.4/lib/jekyll/site.rb:175:in `block in generate'
        from /home/jenkins-agent/.bundle/gems/jekyll-3.8.4/lib/jekyll/site.rb:173:in `each'
        from /home/jenkins-agent/.bundle/gems/jekyll-3.8.4/lib/jekyll/site.rb:173:in `generate'
        from /home/jenkins-agent/.bundle/gems/jekyll-3.8.4/lib/jekyll/site.rb:70:in `process'
        from /home/jenkins-agent/.bundle/gems/jekyll-3.8.4/lib/jekyll/command.rb:28:in `process_site'
        from /home/jenkins-agent/.bundle/gems/jekyll-3.8.4/lib/jekyll/commands/build.rb:65:in `build'
        from /home/jenkins-agent/.bundle/gems/jekyll-3.8.4/lib/jekyll/commands/build.rb:36:in `process'
        from /home/jenkins-agent/.bundle/gems/jekyll-3.8.4/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        from /home/jenkins-agent/.bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from /home/jenkins-agent/.bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from /home/jenkins-agent/.bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from /home/jenkins-agent/.bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from /home/jenkins-agent/.bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from /home/jenkins-agent/.bundle/gems/jekyll-3.8.4/exe/jekyll:15:in `<top (required)>'
        from /home/jenkins-agent/.bundle/bin/jekyll:23:in `load'
        from /home/jenkins-agent/.bundle/bin/jekyll:23:in `<main>'
    make: *** [build] Error 1
    Makefile:19: recipe for target 'build' failed
```

as seen on http://build.ros.org/job/doc_rosindex/78/console

The safe navigation operator could also be used but this is a bit
quicker for most people to grok and doesn't require us to invert the
conditional.

Pending approval and merge we should trigger a job immediately to make sure this is sufficient for the entire dataset. I mused on building it locally but it made sense that if it works we ought not waste the build time by not deploying it.

### CODE REVIEW

**Review by hidmic — APPROVED** [review]
LGTM, thanks! We badly need a suite of unit tests for this project.

**Review by apojomovsky — APPROVED** [review]
Uff, I'm sorry for that.
This LGTM too!

**Comment by nuclearsandwich** [comment]
[Hold on to your butts](https://butt.holdings) [Build Status](http://build.ros.org/job/doc_rosindex/79/)

**Comment by apojomovsky** [comment]
Hm, build seems to be failing for a reason non related to this PR:
```
13:34:26 0xB01FA116
13:34:26 [91mgpg: requesting key B01FA116 from hkp server pool.sks-keyservers.net
13:34:26 [0mgpgkeys: key B01FA116 can't be retrieved
13:34:38 [91mgpg: no valid OpenPGP data found.
13:34:38 gpg: Total number processed: 0
13:34:38 gpg: keyserver communications error: keyserver helper general error
13:34:38 [0m[91mgpg: keyserver communications error: unknown pubkey algorithm
13:34:38 gpg: keyserver receive failed: unknown pubkey algorithm
13:34:38 [0mRemoving intermediate container 9242c4b7188e
13:34:38 The command '/bin/sh -c apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-key 0xB01FA116' returned a non-zero code: 2
13:34:38 Build step 'Execute shell' marked build as failure
13:34:38 Build did not succeed and the project is configured to only push after a successful build, so no pushing will occur.
13:34:38 Finished: FAILURE
```
I tried to relaunch it but just figured that my credentials for `ci.ros2.org` are differents than the one for `build.ros2.org`

**Comment by nuclearsandwich** [comment]
I was seeing issues like this for a different key this morning.

**Comment by tfoote** [comment]
Yeah, the keyservers go down periodically :-( 
We've had a lot of back and forth about the best urls to recommend using in our install instructions but they all occasionally have downtime.

**Pull request merged**
