### PR TITLE
Make the docs repositories sphinx repositories. 

### PR DESCRIPTION
**Pull request by gonzodepedro**
As suggested on #112 and ros2/ros2_documentation#10 it provides support for pulling Sphinx projects 
Related to ros2/ros2_documentation#26

### CODE REVIEW

**Review by hidmic — APPROVED** [review]
LGTM

**Comment by hidmic** [comment]
Ok, going in.

**Comment by dirk-thomas** [comment]
Please squash merge in the future if you don't need to maintain separate commits.

**Comment by hidmic** [comment]
Argh, yes, sorry.

**Pull request merged**
