### PR TITLE
Update packages.ros.org apt key.

### PR DESCRIPTION
**Pull request by hidmic**
Same as https://github.com/ros-infrastructure/rosindex/pull/146, but updated after https://discourse.ros.org/t/new-gpg-keys-deployed-for-packages-ros-org/9454. Key file was pulled from http://packages.ros.org/.

### CODE REVIEW

**Review by tfoote — APPROVED** [review]
I'm assuming it's the right key, it's hard to tell with the binary. Maybe it would make sense to switch to use the ascii armored key instead for easier introspection: http://packages.ros.org/ros.asc

**Comment by hidmic** [comment]
> Maybe it would make sense to switch to use the ascii armored key instead for easier introspection: http://packages.ros.org/ros.asc

``` 
wget -q -O - http://packages.ros.org/ros.asc | sudo apt-key add -
```

? Or versioned like this?

**Comment by tfoote** [comment]
I would suggest fully embedding it like the pr, but just use the ascii version instead of the binary version.

**Comment by hidmic** [comment]
@tfoote PTAL, force pushed as it didn't make sense to keep the old commit.

**Review by tfoote — APPROVED** [review]

**Pull request merged**
